FROM resin/%%RESIN_MACHINE_NAME%%-golang:1.9-stretch AS build

WORKDIR /go/src/github.com/resin-btc-golang/app

COPY /app ./

RUN go build

FROM resin/%%RESIN_MACHINE_NAME%%-debian:stretch

COPY --from=build /go/src/github.com/resin-btc-golang/app/ .

CMD ./app